/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public/route'
import { Route as PrivateRouteImport } from './routes/_private/route'
import { Route as IndexImport } from './routes/index'
import { Route as PublicRegisterImport } from './routes/_public/register'
import { Route as PublicLoginImport } from './routes/_public/login'
import { Route as PrivateDashboardImport } from './routes/_private/dashboard'
import { Route as PrivateGameMenuImport } from './routes/_private/GameMenu'
import { Route as PrivateGameConfigsGameImport } from './routes/_private/game/configs/$game'
import { Route as PrivateGameMemoryGameSingleModeMemory1vs1Import } from './routes/_private/game/_memoryGame/singleMode/memory1vs1'
import { Route as PrivateGameMemoryGame1vs1ModeMemoryImport } from './routes/_private/game/_memoryGame/1vs1Mode/memory'
import { Route as PrivateGameHangmanGameSingleModeHangmanImport } from './routes/_private/game/_hangmanGame/singleMode/hangman'
import { Route as PrivateGameHangmanGame1vs1ModeHangman1vs1Import } from './routes/_private/game/_hangmanGame/1vs1Mode/hangman1vs1'

// Create/Update Routes

const PublicRouteRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRouteRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicRegisterRoute = PublicRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)

const PublicLoginRoute = PublicLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)

const PrivateDashboardRoute = PrivateDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const PrivateGameMenuRoute = PrivateGameMenuImport.update({
  id: '/GameMenu',
  path: '/GameMenu',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const PrivateGameConfigsGameRoute = PrivateGameConfigsGameImport.update({
  id: '/game/configs/$game',
  path: '/game/configs/$game',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const PrivateGameMemoryGameSingleModeMemory1vs1Route =
  PrivateGameMemoryGameSingleModeMemory1vs1Import.update({
    id: '/game/_memoryGame/singleMode/memory1vs1',
    path: '/game/singleMode/memory1vs1',
    getParentRoute: () => PrivateRouteRoute,
  } as any)

const PrivateGameMemoryGame1vs1ModeMemoryRoute =
  PrivateGameMemoryGame1vs1ModeMemoryImport.update({
    id: '/game/_memoryGame/1vs1Mode/memory',
    path: '/game/1vs1Mode/memory',
    getParentRoute: () => PrivateRouteRoute,
  } as any)

const PrivateGameHangmanGameSingleModeHangmanRoute =
  PrivateGameHangmanGameSingleModeHangmanImport.update({
    id: '/game/_hangmanGame/singleMode/hangman',
    path: '/game/singleMode/hangman',
    getParentRoute: () => PrivateRouteRoute,
  } as any)

const PrivateGameHangmanGame1vs1ModeHangman1vs1Route =
  PrivateGameHangmanGame1vs1ModeHangman1vs1Import.update({
    id: '/game/_hangmanGame/1vs1Mode/hangman1vs1',
    path: '/game/1vs1Mode/hangman1vs1',
    getParentRoute: () => PrivateRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRoute
    }
    '/_private/GameMenu': {
      id: '/_private/GameMenu'
      path: '/GameMenu'
      fullPath: '/GameMenu'
      preLoaderRoute: typeof PrivateGameMenuImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof PublicRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterImport
      parentRoute: typeof PublicRouteImport
    }
    '/_private/game/configs/$game': {
      id: '/_private/game/configs/$game'
      path: '/game/configs/$game'
      fullPath: '/game/configs/$game'
      preLoaderRoute: typeof PrivateGameConfigsGameImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/game/_hangmanGame/1vs1Mode/hangman1vs1': {
      id: '/_private/game/_hangmanGame/1vs1Mode/hangman1vs1'
      path: '/game/1vs1Mode/hangman1vs1'
      fullPath: '/game/1vs1Mode/hangman1vs1'
      preLoaderRoute: typeof PrivateGameHangmanGame1vs1ModeHangman1vs1Import
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/game/_hangmanGame/singleMode/hangman': {
      id: '/_private/game/_hangmanGame/singleMode/hangman'
      path: '/game/singleMode/hangman'
      fullPath: '/game/singleMode/hangman'
      preLoaderRoute: typeof PrivateGameHangmanGameSingleModeHangmanImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/game/_memoryGame/1vs1Mode/memory': {
      id: '/_private/game/_memoryGame/1vs1Mode/memory'
      path: '/game/1vs1Mode/memory'
      fullPath: '/game/1vs1Mode/memory'
      preLoaderRoute: typeof PrivateGameMemoryGame1vs1ModeMemoryImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/game/_memoryGame/singleMode/memory1vs1': {
      id: '/_private/game/_memoryGame/singleMode/memory1vs1'
      path: '/game/singleMode/memory1vs1'
      fullPath: '/game/singleMode/memory1vs1'
      preLoaderRoute: typeof PrivateGameMemoryGameSingleModeMemory1vs1Import
      parentRoute: typeof PrivateRouteImport
    }
  }
}

// Create and export the route tree

interface PrivateRouteRouteChildren {
  PrivateGameMenuRoute: typeof PrivateGameMenuRoute
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateGameConfigsGameRoute: typeof PrivateGameConfigsGameRoute
  PrivateGameHangmanGame1vs1ModeHangman1vs1Route: typeof PrivateGameHangmanGame1vs1ModeHangman1vs1Route
  PrivateGameHangmanGameSingleModeHangmanRoute: typeof PrivateGameHangmanGameSingleModeHangmanRoute
  PrivateGameMemoryGame1vs1ModeMemoryRoute: typeof PrivateGameMemoryGame1vs1ModeMemoryRoute
  PrivateGameMemoryGameSingleModeMemory1vs1Route: typeof PrivateGameMemoryGameSingleModeMemory1vs1Route
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateGameMenuRoute: PrivateGameMenuRoute,
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateGameConfigsGameRoute: PrivateGameConfigsGameRoute,
  PrivateGameHangmanGame1vs1ModeHangman1vs1Route:
    PrivateGameHangmanGame1vs1ModeHangman1vs1Route,
  PrivateGameHangmanGameSingleModeHangmanRoute:
    PrivateGameHangmanGameSingleModeHangmanRoute,
  PrivateGameMemoryGame1vs1ModeMemoryRoute:
    PrivateGameMemoryGame1vs1ModeMemoryRoute,
  PrivateGameMemoryGameSingleModeMemory1vs1Route:
    PrivateGameMemoryGameSingleModeMemory1vs1Route,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PublicRouteRouteWithChildren
  '/GameMenu': typeof PrivateGameMenuRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/game/configs/$game': typeof PrivateGameConfigsGameRoute
  '/game/1vs1Mode/hangman1vs1': typeof PrivateGameHangmanGame1vs1ModeHangman1vs1Route
  '/game/singleMode/hangman': typeof PrivateGameHangmanGameSingleModeHangmanRoute
  '/game/1vs1Mode/memory': typeof PrivateGameMemoryGame1vs1ModeMemoryRoute
  '/game/singleMode/memory1vs1': typeof PrivateGameMemoryGameSingleModeMemory1vs1Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PublicRouteRouteWithChildren
  '/GameMenu': typeof PrivateGameMenuRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/game/configs/$game': typeof PrivateGameConfigsGameRoute
  '/game/1vs1Mode/hangman1vs1': typeof PrivateGameHangmanGame1vs1ModeHangman1vs1Route
  '/game/singleMode/hangman': typeof PrivateGameHangmanGameSingleModeHangmanRoute
  '/game/1vs1Mode/memory': typeof PrivateGameMemoryGame1vs1ModeMemoryRoute
  '/game/singleMode/memory1vs1': typeof PrivateGameMemoryGameSingleModeMemory1vs1Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/GameMenu': typeof PrivateGameMenuRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_private/game/configs/$game': typeof PrivateGameConfigsGameRoute
  '/_private/game/_hangmanGame/1vs1Mode/hangman1vs1': typeof PrivateGameHangmanGame1vs1ModeHangman1vs1Route
  '/_private/game/_hangmanGame/singleMode/hangman': typeof PrivateGameHangmanGameSingleModeHangmanRoute
  '/_private/game/_memoryGame/1vs1Mode/memory': typeof PrivateGameMemoryGame1vs1ModeMemoryRoute
  '/_private/game/_memoryGame/singleMode/memory1vs1': typeof PrivateGameMemoryGameSingleModeMemory1vs1Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/GameMenu'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/game/configs/$game'
    | '/game/1vs1Mode/hangman1vs1'
    | '/game/singleMode/hangman'
    | '/game/1vs1Mode/memory'
    | '/game/singleMode/memory1vs1'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/GameMenu'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/game/configs/$game'
    | '/game/1vs1Mode/hangman1vs1'
    | '/game/singleMode/hangman'
    | '/game/1vs1Mode/memory'
    | '/game/singleMode/memory1vs1'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_private/GameMenu'
    | '/_private/dashboard'
    | '/_public/login'
    | '/_public/register'
    | '/_private/game/configs/$game'
    | '/_private/game/_hangmanGame/1vs1Mode/hangman1vs1'
    | '/_private/game/_hangmanGame/singleMode/hangman'
    | '/_private/game/_memoryGame/1vs1Mode/memory'
    | '/_private/game/_memoryGame/singleMode/memory1vs1'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_private",
        "/_public"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_private": {
      "filePath": "_private/route.tsx",
      "children": [
        "/_private/GameMenu",
        "/_private/dashboard",
        "/_private/game/configs/$game",
        "/_private/game/_hangmanGame/1vs1Mode/hangman1vs1",
        "/_private/game/_hangmanGame/singleMode/hangman",
        "/_private/game/_memoryGame/1vs1Mode/memory",
        "/_private/game/_memoryGame/singleMode/memory1vs1"
      ]
    },
    "/_public": {
      "filePath": "_public/route.tsx",
      "children": [
        "/_public/login",
        "/_public/register"
      ]
    },
    "/_private/GameMenu": {
      "filePath": "_private/GameMenu.tsx",
      "parent": "/_private"
    },
    "/_private/dashboard": {
      "filePath": "_private/dashboard.tsx",
      "parent": "/_private"
    },
    "/_public/login": {
      "filePath": "_public/login.tsx",
      "parent": "/_public"
    },
    "/_public/register": {
      "filePath": "_public/register.tsx",
      "parent": "/_public"
    },
    "/_private/game/configs/$game": {
      "filePath": "_private/game/configs/$game.tsx",
      "parent": "/_private"
    },
    "/_private/game/_hangmanGame/1vs1Mode/hangman1vs1": {
      "filePath": "_private/game/_hangmanGame/1vs1Mode/hangman1vs1.tsx",
      "parent": "/_private"
    },
    "/_private/game/_hangmanGame/singleMode/hangman": {
      "filePath": "_private/game/_hangmanGame/singleMode/hangman.tsx",
      "parent": "/_private"
    },
    "/_private/game/_memoryGame/1vs1Mode/memory": {
      "filePath": "_private/game/_memoryGame/1vs1Mode/memory.tsx",
      "parent": "/_private"
    },
    "/_private/game/_memoryGame/singleMode/memory1vs1": {
      "filePath": "_private/game/_memoryGame/singleMode/memory1vs1.tsx",
      "parent": "/_private"
    }
  }
}
ROUTE_MANIFEST_END */
